version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "7070:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/src/app/static
    depends_on:
      - web

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_questions_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_questions_data: